### ISSUE TITLE
Add ability to generate tokens

### ISSUE THREAD

**Issue by DaanRademaker** [godatadriven/databricks-cdk#809]
I wrote some code to be able to generate tokens in cdk. 
The tricky thing with tokens is that they have to be created new every time they are deployed, this is because we cannot return the actual token_value from a request to the databricks api (I assume this is for safety reasons). 

The implementation can be found here: 
https://github.com/godatadriven/databricks-cdk/pull/808

**Comment by ffinfo** [comment]
fixed in: https://github.com/godatadriven/databricks-cdk/pull/808
