### ISSUE TITLE
Retrieve token_value from Token construct

### ISSUE THREAD

**Issue by DaanRademaker** [godatadriven/databricks-cdk#819]
Currently I am not able to get the generated token_value from the Construct. Looking at for example the credentials construct I see that there is a public function attached to return attribute string. Would this be required for token too?

**Comment by DaanRademaker** [comment]
See pull request: https://github.com/godatadriven/databricks-cdk/pull/818

**Comment by ffinfo** [comment]
since it's a secure string this should never be done in plain text. Must be stored in parameter store of secret manager from the deploy lambda

**Comment by DaanRademaker** [comment]
One  of the issues I am finding is that you cannot create a ssm paramater with a secure string from a CDK application.

**Comment by DaanRademaker** [comment]
I don't seem to be able to create a param with a secure string, this is not possible in cloudformation templates.
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ssm/README.html#creating-new-ssm-parameters-in-your-cdk-app

**Comment by DaanRademaker** [comment]
So only option would be to use secret manager directly.

**Comment by ffinfo** [comment]
fixed by #911
